"""
Model Analyzer Script
Auto-Deployment ML Models Project

This script inspects a model placed in the 'input_models' directory.
It generates an initial audit report detailing the model's structure,
type, and basic properties.
"""

import os
import joblib
import json
import logging
from datetime import datetime
import pandas as pd
import numpy as np
import inspect

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s',
    handlers=[
        logging.FileHandler('model_analysis.log'),
        logging.StreamHandler()
    ]
)
logger = logging.getLogger(__name__)

INPUT_DIR = 'input_models'
REPORT_DIR = 'reports'
REPORT_FILE = os.path.join(REPORT_DIR, 'initial_audit.md')

def get_model_size(file_path):
    """Get file size in MB"""
    size_bytes = os.path.getsize(file_path)
    return size_bytes / (1024 * 1024)

def inspect_model(model_path):
    """Inspect the model object"""
    try:
        model = joblib.load(model_path)
        
        info = {
            "type": type(model).__name__,
            "module": type(model).__module__,
            "params": model.get_params() if hasattr(model, "get_params") else "N/A",
            "has_predict": hasattr(model, "predict"),
            "has_predict_proba": hasattr(model, "predict_proba"),
            "attributes": [a for a in dir(model) if not a.startswith('_') and not callable(getattr(model, a))]
        }

        # Check for companion files
        input_dir = os.path.dirname(model_path)
        info["has_validation_data"] = os.path.exists(os.path.join(input_dir, "validation.csv"))
        info["has_config"] = os.path.exists(os.path.join(input_dir, "config.json"))
        
        # Try to infer input shape if possible (sklearn specific)
        if hasattr(model, "n_features_in_"):
            info["n_features"] = model.n_features_in_
        elif hasattr(model, "n_features_"):
            info["n_features"] = model.n_features_
        else:
            info["n_features"] = "Unknown (Could not infer from model attributes)"
            
        if hasattr(model, "feature_names_in_"):
            info["feature_names"] = list(model.feature_names_in_)
        else:
            info["feature_names"] = "Unknown"
            
        return info, model
    except Exception as e:
        logger.error(f"Failed to load or inspect model: {str(e)}")
        return None, None

def generate_report(model_path, info):
    """Generate the Markdown report"""
    filename = os.path.basename(model_path)
    file_size = get_model_size(model_path)
    
    report = f"""# 🧐 Model Initial Audit Report

**Date:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
**File:** `{filename}`
**Size:** {file_size:.2f} MB

## 1. Model Identity
- **Type:** `{info['type']}`
- **Library:** `{info['module']}`
- **Input Features:** `{info['n_features']}`
- **Validation Data:** {'✅ Present' if info.get('has_validation_data') else '❌ Missing (Will use random noise)'}
- **Configuration:** {'✅ Present' if info.get('has_config') else '❌ Missing (Using defaults)'}

## 2. Capabilities
| Capability | Status |
| :--- | :--- |
| `predict()` | {'✅ Yes' if info['has_predict'] else '❌ No'} |
| `predict_proba()` | {'✅ Yes' if info['has_predict_proba'] else '❌ No'} |

## 3. Configuration
```json
{json.dumps(info['params'], indent=2)}
```

## 4. Expected Features
{info['feature_names'] if isinstance(info['feature_names'], list) else 'No feature names metadata found.'}

---
*This report was automatically generated by the Auto-Deployment System.*
"""
    
    os.makedirs(REPORT_DIR, exist_ok=True)
    with open(REPORT_FILE, 'w', encoding='utf-8') as f:
        f.write(report)
    
    logger.info(f"Report generated: {REPORT_FILE}")
    return REPORT_FILE

def main():
    logger.info("Starting Model Analysis...")
    
    # Find model in input directory
    if not os.path.exists(INPUT_DIR):
        os.makedirs(INPUT_DIR)
        logger.warning(f"Created {INPUT_DIR}. Please place a model file there.")
        return
        
    files = [f for f in os.listdir(INPUT_DIR) if f.endswith(('.pkl', '.joblib', '.sav'))]
    
    if not files:
        logger.warning(f"No model files found in {INPUT_DIR}")
        return
    
    # Pick the first one for now
    model_file = files[0]
    model_path = os.path.join(INPUT_DIR, model_file)
    logger.info(f"Analyzing {model_path}...")
    
    info, model = inspect_model(model_path)
    
    if info:
        report_path = generate_report(model_path, info)
        print(f"✅ Analysis Complete. Report saved to: {report_path}")
    else:
        print("❌ Analysis Failed.")

if __name__ == "__main__":
    main()
